module.exports = {
  someSidebar: [
    {
      "Getting Started": ["intro", "mission", "glossary", "options-strategies"],
      "PSY Roadmap": ["roadmap"],
      "Amercian Style Protocol (V1)": ["arch-option-types", "arch-put-call", "american-how-it-works"],
      "European Style Protocol (V1)": ["european-how-it-works"],
      "Program Integration": ["program-integration-start"],
      Clients: [
        "client-integration-overview",
        {
          JavaScript: [{
            type: 'autogenerated',
            dirName: 'javascript-api'
          }],
        },
        {
          Rust: ["rust-start"],
        },
      ],
      Designers: ["design-logos-fonts"],
      "Devnet Testing": [
        "devnet-tokens",
        "beta-test-for",
        "devnet-beta-testing",
      ],
      "PSY Token": ["tokenomics", "governance"],
      "Team": ["team"],
    },
    "faq",
  ],
};
