module.exports = {
  someSidebar: [
    {
      "Getting Started": ["intro", "mission", "glossary", "options-strategies"],
      "Architecture Design": ["arch-option-types", "arch-put-call"],
      "Amercian Style Protocol (V1)": ["american-how-it-works"],
      "Program Integration": ["program-integration-start"],
      Clients: [
        "client-integration-overview",
        {
          JavaScript: [{
            type: 'autogenerated',
            dirName: 'javascript-api'
          }],
        },
        {
          Rust: ["rust-start"],
        },
      ],
      Designers: ["design-fonts-styles"],
      "Devnet Testing": [
        "devnet-tokens",
        "beta-test-for",
        "devnet-beta-testing",
      ],
      "PSY Token": ["token-incentives"],
    },
    "faq",
  ],
};
